import{a as w,S as B,i as l}from"./assets/vendor-1AYLTIiv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const M="50314291-2088fdeaba0ad7602a74f6941",S="https://pixabay.com/api/";function m(s,r=1,e=40){const n={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e};return w.get(S,{params:n})}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.getElementById("loadMoreBtn");let f=null;function L(s){const r=s.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    `).join("");p.insertAdjacentHTML("beforeend",r),f?f.refresh():f=new B(".gallery a")}function E(){p.innerHTML=""}function b(){g.classList.remove("hidden")}function a(){g.classList.add("hidden")}function v(){y.classList.remove("hidden")}function h(){y.classList.add("hidden")}const q=document.querySelector("#searchForm"),R=document.querySelector("#searchInput"),$=document.getElementById("loadMoreBtn");let i="",d=1,c=40;q.addEventListener("submit",s=>{s.preventDefault(),i=R.value.trim(),i&&(d=1,c=40,E(),h(),b(),m(i,d,c).then(r=>{const e=r.data.hits;if(e.length===0){l.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}L(e),a(),v(),c=20}).catch(r=>{console.error("Fetch error:",r),l.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),a()}))});$.addEventListener("click",()=>{d++,b(),h(),m(i,d,c).then(s=>{const r=s.data.hits;if(r.length===0){l.info({title:"No More Results",message:"No more images found."}),a(),h();return}L(r),a(),v();const e=document.querySelector(".gallery a");if(e){const n=e.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}).catch(s=>{console.error("Fetch error:",s),l.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),a()})});
//# sourceMappingURL=index.js.map
