import{a as E,S as M,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const R="50314291-2088fdeaba0ad7602a74f6941",B="https://pixabay.com/api/";async function m(s,r=1,t=40){const n={key:R,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t};try{return(await E.get(B,{params:n})).data}catch(e){throw console.error("Fetch error:",e),e}}const p=document.querySelector(".gallery"),y=document.querySelector(".loader"),L=document.getElementById("loadMoreBtn");let h=null;function b(s){const r=s.map(t=>`
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </a>
    `).join("");p.insertAdjacentHTML("beforeend",r),h?h.refresh():h=new M(".gallery a")}function P(){p.innerHTML=""}function w(){y.classList.remove("hidden")}function i(){y.classList.add("hidden")}function v(){L.classList.remove("hidden")}function l(){L.classList.add("hidden")}const S=document.querySelector("#searchForm"),q=document.querySelector("#searchInput"),$=document.getElementById("loadMoreBtn");let u="",a=1,d=40,g=0;S.addEventListener("submit",async s=>{if(s.preventDefault(),u=q.value.trim(),!!u){a=1,P(),l(),w();try{const r=await m(u,a,d),t=r.hits;if(g=r.totalHits,t.length===0){c.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i();return}b(t),i();const n=Math.ceil(g/d);a>=n?l():v(),d=20}catch(r){console.error("Error fetching images:",r),c.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),i()}}});$.addEventListener("click",async()=>{a++,w(),l();try{const r=(await m(u,a,d)).hits;if(r.length===0){c.info({title:"No More Results",message:"No more images found.",position:"topRight"}),i(),l();return}b(r),i();const t=Math.ceil(g/d);a>=t?(l(),c.info({title:"End of Results",message:"You have reached the end of the search results.",position:"topRight"})):v();const n=document.querySelector(".gallery a");if(n){const e=n.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(s){console.error("Error fetching images:",s),c.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),i()}});
//# sourceMappingURL=index.js.map
