import{a as v,S,i as l}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const B="50314291-2088fdeaba0ad7602a74f6941",E="https://pixabay.com/api/";async function p(n,r=1,t=40){const s={key:B,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t};try{return(await v.get(E,{params:s})).data}catch(e){throw console.error("Error fetching images from Pixabay:",e),e}}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.getElementById("loadMoreBtn");let f=null;function L(n){const r=n.map(t=>`
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </a>
    `).join("");h.insertAdjacentHTML("beforeend",r),f?f.refresh():f=new S(".gallery a")}function M(){h.innerHTML=""}function b(){g.classList.remove("hidden")}function a(){g.classList.add("hidden")}function w(){y.classList.remove("hidden")}function m(){y.classList.add("hidden")}const P=document.querySelector("#searchForm"),q=document.querySelector("#searchInput"),R=document.getElementById("loadMoreBtn");let i="",d=1,c=40;P.addEventListener("submit",async n=>{if(n.preventDefault(),i=q.value.trim(),!!i){d=1,c=40,M(),m(),b();try{const t=(await p(i,d,c)).hits;if(t.length===0){l.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}L(t),a(),w(),c=20}catch(r){console.error("Fetch error:",r),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),a()}}});R.addEventListener("click",async()=>{d++,b(),m();try{const r=(await p(i,d,c)).hits;if(r.length===0){l.info({title:"No More Results",message:"No more images found."}),a(),m();return}L(r),a(),w();const t=document.querySelector(".gallery a");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}catch(n){console.error("Fetch error:",n),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),a()}});
//# sourceMappingURL=index.js.map
